version: '3.11'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile


    command: gunicorn zooworld.wsgi:application --bind 0.0.0.0:8000

    ports:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
    dbdata:
    static_volume:
  