# Generated by Django 5.0.2 on 2024-02-18 15:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('ItemCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('product_type', models.CharField(choices=[('FOOD', 'food'), ('SNACKS', 'snacks'), ('LITTER', 'litter'), ('TOYS', 'toys'), ('MEDECINE', 'medecine'), ('GROOMING', 'grooming'), ('OTHER', 'other')], max_length=15)),
                ('pet_type', models.CharField(choices=[('CATS', 'cats'), ('DOGS', 'dogs'), ('RODENTS', 'rodents'), ('FISH', 'fish'), ('BIRDS', 'birds'), ('MULTIPLE', 'multiple'), ('OTHER', 'other')], max_length=15)),
                ('brand', models.CharField(default='brand', max_length=50)),
                ('weight', models.IntegerField(default=1)),
                ('is_dry', models.BooleanField(default=True, null=True)),
                ('importance', models.CharField(choices=[('MUST', 'must'), ('HIGH_DEMAND', 'high_demand'), ('AVERAGE', 'Average'), ('NOT_IMPORTANT', 'not_important')], max_length=15)),
                ('planned_amount', models.IntegerField(default=0)),
                ('yellowzone_high_border', models.IntegerField(blank=True, null=True)),
                ('yellowzone_low_border', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_date', models.DateField(default=datetime.datetime.now)),
                ('check_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('check_cash', models.BooleanField(default=False)),
                ('is_issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('supply_delivery_date', models.DateField()),
                ('supply_name', models.CharField(max_length=50)),
                ('supply_checked', models.BooleanField(default=False)),
                ('supply_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('in_store', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('in_paycheck', models.BooleanField(default=False)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('supply_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_category', to='products.itemcategory')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_supply', to='products.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_markup', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_percent_markup', models.IntegerField(default=0)),
                ('product_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='products.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percent_markup', models.IntegerField(default=0)),
                ('new_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.price')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('sold_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField(default=datetime.datetime.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supply_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percent_discount', models.IntegerField(default=0)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_item_in_category', to='products.itemcategory')),
                ('item_in_storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell_data', to='products.item')),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_paycheck', to='products.paycheck')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItemProxy',
            fields=[
                ('p_sold_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_supply_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('p_percent_discount', models.IntegerField(default=0)),
                ('p_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_sold_item_in_category', to='products.itemcategory')),
                ('p_item_in_storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_sell_data', to='products.item')),
                ('p_paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_items_in_paycheck', to='products.paycheck')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supply', models.ManyToManyField(related_name='supplier_data', to='products.supply')),
            ],
        ),
    ]
