# Generated by Django 5.0.2 on 2024-02-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
