# Generated by Django 5.0.2 on 2024-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='goods_by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
