# Generated by Django 5.0.2 on 2024-02-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_itemcategory_goods_by_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldWeightItemProxy',
            fields=[
                ('p_sold_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_weight', models.IntegerField(default=0)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_supply_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('p_percent_discount', models.IntegerField(default=0)),
                ('p_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_w_sold_item_in_category', to='products.itemcategory')),
                ('p_item_in_storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_w_sell_data', to='products.item')),
                ('p_paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_w_items_in_paycheck', to='products.paycheck')),
            ],
        ),
    ]
