# Generated by Django 5.0.2 on 2024-02-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_soldweightitemproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldweightitemproxy',
            name='p_item_in_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_w_sell_data', to='products.item'),
        ),
    ]
