# Generated by Django 5.0.2 on 2024-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_soldweightitemproxy_p_item_in_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldweightitemproxy',
            name='p_price_data',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='soldweightitemproxy',
            name='p_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
