# Generated by Django 5.0.2 on 2024-02-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_soldweightitemproxy_p_price_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldweightitemproxy',
            name='p_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
