# Generated by Django 5.0.2 on 2024-02-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_solditem_item_in_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='sold_by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
