# Generated by Django 5.0.2 on 2024-02-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_solditem_sold_by_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='revision_supply',
            field=models.BooleanField(default=False),
        ),
    ]
